/**
 * LUT-browser previews: one fixed reference frame drawn through each LUT, the
 * way DaVinci Resolve's and Premiere's LUT browsers preview a grade without
 * applying it to your own footage.
 *
 * Everything here is assembly of pieces that already existed — LutRenderer
 * for the draw, cube-cache for the fetch/parse — plus a bundled reference
 * image and two caches per size.
 *
 * **Its own GL context, on purpose.** The renderer below lives on a detached
 * canvas that nothing else touches, so previews never share a canvas or a
 * WebGLRenderingContext with the live video/image preview's own LutRenderer.
 * One context is shared across *all* of them though: a context per LUT would
 * blow past the browser's ~16-live-context limit on any real library.
 */

import { isWebGL2Available, LutRenderer } from './webgl-lut'
import { loadCube } from './cube-cache'

/** Bundled at apps/web/public/lut-reference.jpg, generated by
 *  apps/web/scripts/generate-lut-reference.mjs — see that file for what the
 *  image is, where the photograph came from, its licence, and how to swap
 *  it. 3:2. */
export const REFERENCE_IMAGE_SRC = '/lut-reference.jpg'

/** 2x the largest place a row thumbnail is displayed (48x32 in Settings), so
 *  it stays crisp on a retina panel while still being a glance-preview rather
 *  than a picture. */
const THUMBNAIL_WIDTH = 192
const THUMBNAIL_HEIGHT = 128

/** The click-to-zoom view in Settings. Rendered rather than upscaled from the
 *  thumbnail — an upscaled 192px swatch is exactly the blur this view exists
 *  to avoid — and at 2x its 480x320 display size, which is also the reference
 *  image's own resolution, so nothing is interpolated up at any stage. */
const PREVIEW_WIDTH = 960
const PREVIEW_HEIGHT = 640

/** At most this many LUTs are fetched/parsed/drawn at once. A library with a
 *  hundred LUTs otherwise opens a hundred simultaneous requests. */
const MAX_CONCURRENT = 4

interface Variant {
  width: number
  height: number
  /** PNG for the small swatch; JPEG for the zoom, where a lossless read-back
   *  of a photograph is ~1MB of base64 held in memory per LUT. */
  type: 'image/png' | 'image/jpeg'
  quality?: number
  /** Rendered data URLs, keyed by LUT id. Same lifetime story as cube-cache:
   *  the .cube behind a LUT never changes, so a frame drawn once is good for
   *  the session. */
  cache: Map<string, string>
  /** In-flight renders, so two surfaces asking for the same LUT at the same
   *  size share one draw. */
  pending: Map<string, Promise<string>>
}

const THUMBNAIL: Variant = {
  width: THUMBNAIL_WIDTH,
  height: THUMBNAIL_HEIGHT,
  type: 'image/png',
  cache: new Map(),
  pending: new Map(),
}

const PREVIEW: Variant = {
  width: PREVIEW_WIDTH,
  height: PREVIEW_HEIGHT,
  type: 'image/jpeg',
  quality: 0.92,
  cache: new Map(),
  pending: new Map(),
}

let referenceImage: Promise<HTMLImageElement> | null = null
let renderer: LutRenderer | null = null
let canvas: HTMLCanvasElement | null = null

let active = 0
const waiting: (() => void)[] = []

function acquire(): Promise<void> {
  if (active < MAX_CONCURRENT) {
    active += 1
    return Promise.resolve()
  }
  return new Promise<void>((resolve) => {
    waiting.push(() => {
      active += 1
      resolve()
    })
  })
}

function release(): void {
  active -= 1
  waiting.shift()?.()
}

function loadReferenceImage(): Promise<HTMLImageElement> {
  if (referenceImage) return referenceImage
  referenceImage = new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve(img)
    img.onerror = () => {
      // Cleared so a later render retries rather than inheriting a
      // permanently-rejected promise.
      referenceImage = null
      reject(new Error('Could not load the LUT reference image'))
    }
    img.src = REFERENCE_IMAGE_SRC
  })
  return referenceImage
}

function getRenderer(): LutRenderer {
  if (!renderer) {
    canvas = document.createElement('canvas')
    canvas.width = THUMBNAIL_WIDTH
    canvas.height = THUMBNAIL_HEIGHT
    renderer = new LutRenderer(canvas)
  }
  return renderer
}

/**
 * Draw the reference frame through one LUT at one size and return it as a
 * data URL.
 *
 * Rejects rather than returning a placeholder when the .cube can't be loaded
 * or WebGL2 is unavailable — an ungraded swatch shown as though it were
 * graded is worse than no swatch, the same call use-lut.ts makes for the
 * live preview.
 */
function renderThrough(
  variant: Variant,
  lutId: string,
  fileUrl: string | null | undefined,
): Promise<string> {
  const cached = variant.cache.get(lutId)
  if (cached) return Promise.resolve(cached)

  const existing = variant.pending.get(lutId)
  if (existing) return existing

  if (!isWebGL2Available()) {
    return Promise.reject(new Error('WebGL2 is not available'))
  }

  const work = (async () => {
    await acquire()
    try {
      const [image, cube] = await Promise.all([
        loadReferenceImage(),
        loadCube(lutId, fileUrl),
      ])

      const instance = getRenderer()
      instance.setLut(cube)
      instance.render(image, variant.width, variant.height)
      // Read back synchronously, in the same task as the draw: the context is
      // created with preserveDrawingBuffer:false, so the drawing buffer is
      // only valid until the next composite. Nothing may await between
      // render() and toDataURL() — and because the context is shared, an
      // await here would let another LUT's setLut/render interleave and each
      // frame would read back the wrong grade.
      const dataUrl = canvas!.toDataURL(variant.type, variant.quality)

      variant.cache.set(lutId, dataUrl)
      return dataUrl
    } finally {
      release()
      variant.pending.delete(lutId)
    }
  })()

  variant.pending.set(lutId, work)
  return work
}

/** Synchronous hit-test, so a row that already has a thumbnail renders it on
 *  its first paint instead of flashing a placeholder. */
export function getCachedLutThumbnail(lutId: string): string | null {
  return THUMBNAIL.cache.get(lutId) ?? null
}

export function renderLutThumbnail(
  lutId: string,
  fileUrl: string | null | undefined,
): Promise<string> {
  return renderThrough(THUMBNAIL, lutId, fileUrl)
}

/** The same, at the zoom view's size. Cached separately from the thumbnail:
 *  re-opening a LUT's zoom in the same session re-renders nothing. */
export function getCachedLutPreview(lutId: string): string | null {
  return PREVIEW.cache.get(lutId) ?? null
}

export function renderLutPreview(
  lutId: string,
  fileUrl: string | null | undefined,
): Promise<string> {
  return renderThrough(PREVIEW, lutId, fileUrl)
}
