/**
 * LUT-browser thumbnails: one fixed reference frame drawn through each LUT,
 * the way DaVinci Resolve's and Premiere's LUT browsers preview a grade
 * without applying it to your own footage.
 *
 * Everything here is assembly of pieces that already existed — LutRenderer
 * for the draw, cube-cache for the fetch/parse — plus a bundled reference
 * image and two caches.
 *
 * **Its own GL context, on purpose.** The renderer below lives on a detached
 * canvas that nothing else touches, so thumbnails never share a canvas or a
 * WebGLRenderingContext with the live video/image preview's own LutRenderer.
 * One context is shared across *all* thumbnails though: a context per LUT
 * would blow past the browser's ~16-live-context limit on any real library.
 */

import { isWebGL2Available, LutRenderer } from './webgl-lut'
import { loadCube } from './cube-cache'

/** Bundled at apps/web/public/lut-reference.png, generated by
 *  apps/web/scripts/generate-lut-reference.mjs — see that file for what the
 *  image is and how to swap it. */
export const REFERENCE_IMAGE_SRC = '/lut-reference.png'

/** The reference image's own size, and 2x the largest place a thumbnail is
 *  displayed (48x32 in Settings), so it stays crisp on a retina panel while
 *  still being a glance-preview rather than a picture. */
const THUMBNAIL_WIDTH = 192
const THUMBNAIL_HEIGHT = 128

/** At most this many LUTs are fetched/parsed/drawn at once. A library with a
 *  hundred LUTs otherwise opens a hundred simultaneous requests. */
const MAX_CONCURRENT = 4

/** Rendered PNG data URLs, keyed by LUT id. Same lifetime story as
 *  cube-cache: the .cube behind a LUT never changes, so a thumbnail drawn
 *  once is good for the session. */
const thumbnailCache = new Map<string, string>()

/** In-flight renders, so two surfaces listing the same LUT share one draw. */
const pending = new Map<string, Promise<string>>()

let referenceImage: Promise<HTMLImageElement> | null = null
let renderer: LutRenderer | null = null
let canvas: HTMLCanvasElement | null = null

let active = 0
const waiting: (() => void)[] = []

function acquire(): Promise<void> {
  if (active < MAX_CONCURRENT) {
    active += 1
    return Promise.resolve()
  }
  return new Promise<void>((resolve) => {
    waiting.push(() => {
      active += 1
      resolve()
    })
  })
}

function release(): void {
  active -= 1
  waiting.shift()?.()
}

function loadReferenceImage(): Promise<HTMLImageElement> {
  if (referenceImage) return referenceImage
  referenceImage = new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve(img)
    img.onerror = () => {
      // Cleared so a later thumbnail retries rather than inheriting a
      // permanently-rejected promise.
      referenceImage = null
      reject(new Error('Could not load the LUT reference image'))
    }
    img.src = REFERENCE_IMAGE_SRC
  })
  return referenceImage
}

function getRenderer(): LutRenderer {
  if (!renderer) {
    canvas = document.createElement('canvas')
    canvas.width = THUMBNAIL_WIDTH
    canvas.height = THUMBNAIL_HEIGHT
    renderer = new LutRenderer(canvas)
  }
  return renderer
}

/** Synchronous hit-test, so a row that already has a thumbnail renders it on
 *  its first paint instead of flashing a placeholder. */
export function getCachedLutThumbnail(lutId: string): string | null {
  return thumbnailCache.get(lutId) ?? null
}

/**
 * Draw the reference frame through one LUT and return it as a PNG data URL.
 *
 * Rejects rather than returning a placeholder when the .cube can't be loaded
 * or WebGL2 is unavailable — an ungraded swatch shown as though it were
 * graded is worse than no swatch, the same call use-lut.ts makes for the
 * live preview.
 */
export function renderLutThumbnail(
  lutId: string,
  fileUrl: string | null | undefined,
): Promise<string> {
  const cached = thumbnailCache.get(lutId)
  if (cached) return Promise.resolve(cached)

  const existing = pending.get(lutId)
  if (existing) return existing

  if (!isWebGL2Available()) {
    return Promise.reject(new Error('WebGL2 is not available'))
  }

  const work = (async () => {
    await acquire()
    try {
      const [image, cube] = await Promise.all([
        loadReferenceImage(),
        loadCube(lutId, fileUrl),
      ])

      const instance = getRenderer()
      instance.setLut(cube)
      instance.render(image, THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT)
      // Read back synchronously, in the same task as the draw: the context is
      // created with preserveDrawingBuffer:false, so the drawing buffer is
      // only valid until the next composite. Nothing may await between
      // render() and toDataURL().
      const dataUrl = canvas!.toDataURL('image/png')

      thumbnailCache.set(lutId, dataUrl)
      return dataUrl
    } finally {
      release()
      pending.delete(lutId)
    }
  })()

  pending.set(lutId, work)
  return work
}
